import { SUB_BLOCK_TYPES as T } from "./subBlockTypes.js";

// ConvEngine block registry.
//
// Every entry maps 1:1 to a ce_* table in the convengine backend. Column names
// below match the JPA entities verbatim (CeIntent, CePromptTemplate, CeRule,
// CeResponse, CeMcpTool, CeMcpPlanner, CePolicy) so the Deploy step can
// serialize canvas state directly into row payloads for /api/v1/config/*.
//
// Adapted structurally from Sim Studio's apps/sim/blocks/registry.ts.

const INTERACTION_MODES = [
  "NORMAL",
  "IDLE",
  "COLLECT",
  "CONFIRM",
  "PROCESSING",
  "FINAL",
  "ERROR",
  "DISAMBIGUATE",
  "FOLLOW_UP",
  "PENDING_ACTION",
  "REVIEW",
];

// ce_rule.phase default is PRE_RESPONSE_RESOLUTION per CeRule entity.
// Ordering below mirrors the 27-step pipeline phases that RulesStep honors.
const RULE_PHASES = [
  "POST_DIALOGUE_ACT",
  "PRE_INTENT_RESOLUTION",
  "POST_INTENT_RESOLUTION",
  "PRE_SCHEMA_EXTRACTION",
  "POST_SCHEMA_EXTRACTION",
  "PRE_AGENT_MCP",
  "POST_AGENT_MCP",
  "PRE_RESPONSE_RESOLUTION",
  "POST_RESPONSE_RESOLUTION",
];

const RESPONSE_TYPES = ["EXACT", "DERIVED"];

export const CE_BLOCKS = {
  intent: {
    type: "intent",
    table: "ce_intent",
    name: "Intent",
    description: "A classifiable user goal routed by IntentResolutionStep.",
    category: "conversation",
    bgColor: "#7c3aed",
    icon: "intent",
    primaryKey: "intent_code",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, placeholder: "e.g. book_flight", required: true },
      { id: "display_name", title: "Display Name", type: T.SHORT_INPUT },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 3, required: true },
      { id: "llm_hint", title: "LLM Hint", type: T.LONG_INPUT, rows: 3 },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  intent_classifier: {
    type: "intent_classifier",
    table: "ce_intent_classifier",
    name: "Intent Classifier",
    description: "Deterministic regex / contains / starts-with classifier used by IntentResolutionStep.",
    category: "routing",
    bgColor: "#f59e0b",
    icon: "rule",
    primaryKey: "classifier_id",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, defaultValue: "UNKNOWN", required: true },
      { id: "rule_type", title: "Rule Type", type: T.DROPDOWN, options: ["REGEX", "CONTAINS", "STARTS_WITH"], defaultValue: "REGEX" },
      { id: "pattern", title: "Pattern", type: T.LONG_INPUT, rows: 3, required: true },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 2 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  prompt_template: {
    type: "prompt_template",
    table: "ce_prompt_template",
    name: "Prompt Template",
    description: "System + user prompt used by a pipeline step's LLM call.",
    category: "conversation",
    bgColor: "#2563eb",
    icon: "prompt",
    primaryKey: "template_id",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, required: true },
      { id: "output_format", title: "Output Format", type: T.SHORT_INPUT, placeholder: "e.g. JSON, TEXT", required: true },
      { id: "interaction_mode", title: "Interaction Mode", type: T.DROPDOWN, options: INTERACTION_MODES, defaultValue: "NORMAL" },
      { id: "system_prompt", title: "System Prompt", type: T.LONG_INPUT, rows: 8, required: true },
      { id: "user_prompt", title: "User Prompt", type: T.LONG_INPUT, rows: 4, required: true },
      { id: "temperature", title: "Temperature", type: T.SLIDER, min: 0, max: 2, step: 0.1, defaultValue: 0 },
      { id: "interaction_contract", title: "Interaction Contract", type: T.JSON, rows: 6 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  rule: {
    type: "rule",
    table: "ce_rule",
    name: "Rule",
    description: "Deterministic transition applied by RulesStep at the given phase.",
    category: "routing",
    bgColor: "#db2777",
    icon: "rule",
    primaryKey: "rule_id",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, required: true },
      { id: "rule_type", title: "Rule Type", type: T.SHORT_INPUT, placeholder: "backend-defined string", required: true },
      { id: "match_pattern", title: "Match Pattern", type: T.LONG_INPUT, rows: 3, required: true },
      { id: "action", title: "Action", type: T.SHORT_INPUT, placeholder: "backend-defined string", required: true },
      { id: "action_value", title: "Action Value", type: T.LONG_INPUT, rows: 2 },
      { id: "phase", title: "Phase", type: T.DROPDOWN, options: RULE_PHASES, defaultValue: "PRE_RESPONSE_RESOLUTION" },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 2 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  response: {
    type: "response",
    table: "ce_response",
    name: "Response",
    description: "Final message template rendered by ResponseResolutionStep.",
    category: "conversation",
    bgColor: "#16a34a",
    icon: "response",
    primaryKey: "response_id",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, required: true },
      { id: "output_format", title: "Output Format", type: T.SHORT_INPUT, required: true },
      { id: "response_type", title: "Response Type", type: T.DROPDOWN, options: RESPONSE_TYPES, defaultValue: "EXACT" },
      { id: "exact_text", title: "Exact Text", type: T.LONG_INPUT, rows: 4 },
      { id: "derivation_hint", title: "Derivation Hint", type: T.LONG_INPUT, rows: 4 },
      { id: "json_schema", title: "JSON Schema", type: T.JSON, rows: 5 },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 2 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  mcp_db_tool: {
    type: "mcp_db_tool",
    table: "ce_mcp_db_tool",
    name: "MCP DB Tool",
    description: "SQL extension of an MCP Tool — dialect, template, param schema, safety knobs.",
    category: "tools",
    bgColor: "#92400e",
    icon: "tool",
    primaryKey: "tool_id",
    subBlocks: [
      { id: "tool_id", title: "Tool ID", type: T.SHORT_INPUT, required: true, placeholder: "FK to ce_mcp_tool.tool_id" },
      { id: "dialect", title: "Dialect", type: T.SHORT_INPUT, required: true, placeholder: "postgres | oracle | sqlite" },
      { id: "sql_template", title: "SQL Template", type: T.LONG_INPUT, rows: 8, required: true },
      { id: "param_schema", title: "Param Schema", type: T.JSON, rows: 6, required: true },
      { id: "allowed_identifiers", title: "Allowed Identifiers", type: T.JSON, rows: 4 },
      { id: "safe_mode", title: "Safe Mode", type: T.SWITCH, defaultValue: true },
      { id: "max_rows", title: "Max Rows", type: T.SLIDER, min: 1, max: 10000, step: 1, defaultValue: 200 },
    ],
    outputs: { handles: ["default"] },
  },

  mcp_tool: {
    type: "mcp_tool",
    table: "ce_mcp_tool",
    name: "MCP Tool",
    description: "External tool registered for McpToolStep orchestration.",
    category: "tools",
    bgColor: "#b45309",
    icon: "tool",
    primaryKey: "tool_id",
    subBlocks: [
      { id: "tool_code", title: "Tool Code", type: T.SHORT_INPUT, required: true },
      { id: "tool_group", title: "Tool Group", type: T.SHORT_INPUT, required: true },
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, required: true },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 3 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  mcp_planner: {
    type: "mcp_planner",
    table: "ce_mcp_planner",
    name: "MCP Planner",
    description: "Planner prompt used by the MCP tool orchestration step.",
    category: "tools",
    bgColor: "#0891b2",
    icon: "planner",
    primaryKey: "planner_id",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, required: true },
      { id: "system_prompt", title: "System Prompt", type: T.LONG_INPUT, rows: 8, required: true },
      { id: "user_prompt", title: "User Prompt", type: T.LONG_INPUT, rows: 4, required: true },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  config: {
    type: "config",
    table: "ce_config",
    name: "Config",
    description: "Generic (config_type, config_key) → config_value store for framework knobs.",
    category: "governance",
    bgColor: "#475569",
    icon: "policy",
    primaryKey: "config_id",
    subBlocks: [
      { id: "config_type", title: "Config Type", type: T.SHORT_INPUT, required: true },
      { id: "config_key", title: "Config Key", type: T.SHORT_INPUT, required: true },
      { id: "config_value", title: "Config Value", type: T.LONG_INPUT, rows: 4, required: true },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  verbose: {
    type: "verbose",
    table: "ce_verbose",
    name: "Verbose",
    description: "Per-step debug/observability message keyed by (intent, state, step).",
    category: "governance",
    bgColor: "#64748b",
    icon: "policy",
    primaryKey: "verbose_id",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, required: true },
      { id: "step_match", title: "Step Match", type: T.SHORT_INPUT, required: true },
      { id: "step_value", title: "Step Value", type: T.SHORT_INPUT, required: true },
      { id: "determinant", title: "Determinant", type: T.SHORT_INPUT, required: true },
      { id: "rule_id", title: "Rule ID", type: T.SHORT_INPUT, placeholder: "optional FK to ce_rule" },
      { id: "tool_code", title: "Tool Code", type: T.SHORT_INPUT, placeholder: "optional FK to ce_mcp_tool" },
      { id: "message", title: "Message", type: T.LONG_INPUT, rows: 3 },
      { id: "error_message", title: "Error Message", type: T.LONG_INPUT, rows: 3 },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  policy: {
    type: "policy",
    table: "ce_policy",
    name: "Policy",
    description: "Guardrail policy evaluated during the pipeline.",
    category: "governance",
    bgColor: "#dc2626",
    icon: "policy",
    primaryKey: "policy_id",
    subBlocks: [
      { id: "rule_type", title: "Rule Type", type: T.SHORT_INPUT, required: true },
      { id: "pattern", title: "Pattern", type: T.LONG_INPUT, rows: 3, required: true },
      { id: "response_text", title: "Response Text", type: T.LONG_INPUT, rows: 3, required: true },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 100, step: 1, defaultValue: 10 },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 2 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  output_schema: {
    type: "output_schema",
    table: "ce_output_schema",
    name: "Output Schema",
    description: "JSON schema the LLM must conform to for a given intent+state.",
    category: "conversation",
    bgColor: "#0284c7",
    icon: "schema",
    primaryKey: "schema_id",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, required: true },
      { id: "schema_type", title: "Schema Type", type: T.SHORT_INPUT, defaultValue: "SCHEMA_JSON" },
      { id: "json_schema", title: "JSON Schema", type: T.JSON, rows: 8, required: true },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 2 },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  container_config: {
    type: "container_config",
    table: "ce_container_config",
    name: "Container Config",
    description: "Maps a collected JSON-schema field to a UI page/section/container.",
    category: "conversation",
    bgColor: "#0891b2",
    icon: "schema",
    primaryKey: "id",
    subBlocks: [
      { id: "intent_code", title: "Intent Code", type: T.SHORT_INPUT, required: true },
      { id: "state_code", title: "State Code", type: T.SHORT_INPUT, required: true },
      { id: "page_id", title: "Page ID", type: T.SHORT_INPUT, required: true },
      { id: "section_id", title: "Section ID", type: T.SHORT_INPUT, required: true },
      { id: "container_id", title: "Container ID", type: T.SHORT_INPUT, required: true },
      { id: "input_param_name", title: "Input Param Name", type: T.SHORT_INPUT, required: true, placeholder: "must match JSON schema field" },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  semantic_entity: {
    type: "semantic_entity",
    table: "ce_semantic_entity",
    name: "Semantic Entity",
    description: "Business-level entity (Customer, Order…) used by the semantic layer.",
    category: "semantic",
    bgColor: "#9333ea",
    icon: "entity",
    primaryKey: "id",
    subBlocks: [
      { id: "entity_name", title: "Entity Name", type: T.SHORT_INPUT, required: true },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 3 },
      { id: "primary_table", title: "Primary Table", type: T.SHORT_INPUT },
      { id: "related_tables", title: "Related Tables", type: T.LONG_INPUT, rows: 2, placeholder: "comma-separated" },
      { id: "synonyms", title: "Synonyms", type: T.LONG_INPUT, rows: 2, placeholder: "comma-separated" },
      { id: "fields_json", title: "Fields JSON", type: T.JSON, rows: 6 },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  semantic_relationship: {
    type: "semantic_relationship",
    table: "ce_semantic_relationship",
    name: "Semantic Relationship",
    description: "Directed edge between two semantic entities (from_table → to_table).",
    category: "semantic",
    bgColor: "#c026d3",
    icon: "edge",
    primaryKey: "id",
    subBlocks: [
      { id: "relationship_name", title: "Relationship Name", type: T.SHORT_INPUT, required: true },
      { id: "description", title: "Description", type: T.LONG_INPUT, rows: 2 },
      { id: "from_table", title: "From Table", type: T.SHORT_INPUT, required: true },
      { id: "from_column", title: "From Column", type: T.SHORT_INPUT, required: true },
      { id: "to_table", title: "To Table", type: T.SHORT_INPUT, required: true },
      { id: "to_column", title: "To Column", type: T.SHORT_INPUT, required: true },
      { id: "relation_type", title: "Relation Type", type: T.SHORT_INPUT, placeholder: "ONE_TO_MANY / MANY_TO_ONE / …" },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  semantic_join_hint: {
    type: "semantic_join_hint",
    table: "ce_semantic_join_hint",
    name: "Semantic Join Hint",
    description: "Suggested join path between two tables for the query optimizer.",
    category: "semantic",
    bgColor: "#a21caf",
    icon: "edge",
    primaryKey: "id",
    subBlocks: [
      { id: "base_table", title: "Base Table", type: T.SHORT_INPUT, required: true },
      { id: "join_table", title: "Join Table", type: T.SHORT_INPUT, required: true },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },

  semantic_value_pattern: {
    type: "semantic_value_pattern",
    table: "ce_semantic_value_pattern",
    name: "Semantic Value Pattern",
    description: "Routes values from one field to another when a prefix pattern matches.",
    category: "semantic",
    bgColor: "#7e22ce",
    icon: "pattern",
    primaryKey: "id",
    subBlocks: [
      { id: "from_field", title: "From Field", type: T.SHORT_INPUT, required: true },
      { id: "to_field", title: "To Field", type: T.SHORT_INPUT, required: true },
      { id: "value_starts_with", title: "Value Starts With", type: T.LONG_INPUT, rows: 2, required: true },
      { id: "priority", title: "Priority", type: T.SLIDER, min: 0, max: 1000, step: 1, defaultValue: 100 },
      { id: "enabled", title: "Enabled", type: T.SWITCH, defaultValue: true },
    ],
    outputs: { handles: ["default"] },
  },
};

export const CE_BLOCK_LIST = Object.values(CE_BLOCKS);

export function getBlockConfig(type) {
  return CE_BLOCKS[type] || null;
}
