export const topNavButtonsConfig = {
  home: {
    disabled: true,
    inactive: true,
    audit_visible: false,
    className: "brand-icon hero-home-btn",
    title: "ConvEngine",
    ariaLabel: "ConvEngine",
    asset: "ce-logo.svg",
    fallbackAsset: "conv.svg",
  },
  chat: {
    disabled: false,
    inactive: false,
    audit_visible: true,
    className: "hero-cache-icon-btn hero-cache-icon-btn-chat",
    title: "Open chat",
    ariaLabel: "Open chat",
    activePage: "chat",
  },
  refresh: {
    disabled: false,
    inactive: false,
    audit_visible: false,
    className: "hero-cache-icon-btn hero-cache-icon-btn-refresh",
    title: "Refresh cache",
    ariaLabel: "Refresh cache",
    loadingTitle: "Refreshing cache...",
    loadingAriaLabel: "Refreshing cache",
  },
  cacheAnalyze: {
    disabled: true,
    inactive: true,
    audit_visible: false,
    className: "hero-cache-icon-btn hero-cache-icon-btn-analyze",
    title: "Open cache analyze",
    ariaLabel: "Open cache analyze",
    activeTitle: "Back to chat",
    activeAriaLabel: "Back to chat",
    activePage: "cache",
  },
  inspectDb: {
    disabled: true,
    inactive: true,
    audit_visible: false,
    className: "hero-cache-icon-btn hero-cache-icon-btn-db",
    title: "Inspect DB schema tables/columns/joins",
    ariaLabel: "Inspect DB schema tables columns joins",
    activePage: "schema",
  },
  semanticBuilder: {
    disabled: false,
    inactive: false,
    audit_visible: false,
    className: "hero-cache-icon-btn hero-cache-icon-btn-semantic",
    title: "Semantic Builder Studio",
    ariaLabel: "Semantic Builder Studio",
    activePage: "semantic_builder",
  },
  semanticDebug: {
    disabled: true,
    inactive: true,
    audit_visible: false,
    className: "hero-cache-icon-btn hero-cache-icon-btn-semantic",
    title: "Semantic Query Debug",
    ariaLabel: "Semantic Query Debug",
    activePage: "semantic_debug",
  },
  pdfExtract: {
    disabled: false,
    inactive: false,
    audit_visible: false,
    className: "hero-cache-icon-btn hero-cache-icon-btn-pdf",
    title: "PDF Extract Studio",
    ariaLabel: "PDF Extract Studio",
    activePage: "pdf_extract",
  },
  ceBuilder: {
    disabled: false,
    inactive: false,
    audit_visible: false,
    className: "hero-cache-icon-btn hero-cache-icon-btn-ce",
    title: "Builder Studio",
    ariaLabel: "Builder Studio",
    activePage: "ce_builder",
  },
  themeToggle: {
    disabled: false,
    inactive: false,
    audit_visible: false,
    lightClassName: "hero-theme-toggle moon",
    darkClassName: "hero-theme-toggle sun",
    lightTitle: "Switch to Dark Mode",
    darkTitle: "Switch to Light Mode",
    lightAriaLabel: "Switch to Dark Mode",
    darkAriaLabel: "Switch to Light Mode",
  },
  auditToggle: {
    disabled: false,
    inactive: false,
    audit_visible: false,
    className: "audit-toggle",
    title: "Open Audit Timeline",
    ariaLabel: "Open Audit Timeline",
  },
};
